-- ============================================================
-- t_all_column data_type update for VF_NC_D_HW_MW-PM
-- NUMERIC: 54 columns  |  VARCHAR: 51 columns
-- Replace <flow_id> and <table_name> before running
-- ============================================================

UPDATE etl.t_all_column
SET data_type = 'NUMERIC'
WHERE flow_id = <flow_id>
  AND table_name = '<table_name>'
  AND object_key IN (
    'Source Protection Group ID',
    'Sink Protection Group ID',
    'Source XPIC Group ID',
    'Sink XPIC Group ID',
    'Source XPIC Group Capacity (Mbit/s)',
    'Sink XPIC Group Capacity (Mbit/s)',
    'Source XPIC Adjoin LinkID',
    'Sink XPIC Adjoin LinkID',
    'Source Frequency(GHz)',
    'Sink Frequency(GHz)',
    'Source NE Frequency (MHz)',
    'Sink NE Frequency (MHz)',
    'Source NE Preset Value of Transmit Power',
    'Sink NE Preset Value of Transmit Power',
    'Source NE Current Value of Transmit Power',
    'Sink NE Current Value of Transmit Power',
    'Source NE Preset Value of Receive Power',
    'Sink NE Preset Value of Receive Power',
    'Source NE Current Value of Receive Power',
    'Sink NE Current Value of Receive Power',
    'Source NE Max Value of Transmit Power of 24-Hour PM',
    'Sink NE Max Value of Transmit Power of 24-Hour PM',
    'Source NE Min Value of Transmit Power of 24-Hour PM',
    'Sink NE Min Value of Transmit Power of 24-Hour PM',
    'Source NE Max Value of Receive Power of 24-Hour PM',
    'Sink NE Max Value of Receive Power of 24-Hour PM',
    'Source NE Min Value of Receive Power of 24-Hour PM',
    'Sink NE Min Value of Receive Power of 24-Hour PM',
    'Source NE Guaranteed E1 Capacity',
    'Sink NE Guaranteed E1 Capacity',
    'Source NE Occupied E1 Capacity',
    'Sink NE Occupied E1 Capacity',
    'Source NE E1 Capacity Usage (%)',
    'Sink NE E1 Capacity Usage (%)',
    'Source NE Ethernet Capacity (Mbit/s)',
    'Sink NE Ethernet Capacity (Mbit/s)',
    'Source NE Max. Ethernet Throughput (kbps)',
    'Sink NE Max. Ethernet Throughput (kbps)',
    'Source NE Min. Ethernet Throughput (kbps)',
    'Sink NE Min. Ethernet Throughput (kbps)',
    'Source NE Average Ethernet Throughput (kbps)',
    'Sink NE Average Ethernet Throughput (kbps)',
    'Source NE ATPC Upper Threshold',
    'Sink NE ATPC Upper Threshold',
    'Source NE ATPC Lower Threshold',
    'Sink NE ATPC Lower Threshold',
    'Source NE ATPC Upper Automatic Threshold',
    'Sink NE ATPC Upper Automatic Threshold',
    'Source NE ATPC Lower Automatic Threshold',
    'Sink NE ATPC Lower Automatic Threshold',
    'Link ID',
    'Site Distance',
    'Source PLA ID',
    'Sink PLA ID'
);

UPDATE etl.t_all_column
SET data_type = 'VARCHAR'
WHERE flow_id = <flow_id>
  AND table_name = '<table_name>'
  AND object_key NOT IN (
    'Source Protection Group ID',
    'Sink Protection Group ID',
    'Source XPIC Group ID',
    'Sink XPIC Group ID',
    'Source XPIC Group Capacity (Mbit/s)',
    'Sink XPIC Group Capacity (Mbit/s)',
    'Source XPIC Adjoin LinkID',
    'Sink XPIC Adjoin LinkID',
    'Source Frequency(GHz)',
    'Sink Frequency(GHz)',
    'Source NE Frequency (MHz)',
    'Sink NE Frequency (MHz)',
    'Source NE Preset Value of Transmit Power',
    'Sink NE Preset Value of Transmit Power',
    'Source NE Current Value of Transmit Power',
    'Sink NE Current Value of Transmit Power',
    'Source NE Preset Value of Receive Power',
    'Sink NE Preset Value of Receive Power',
    'Source NE Current Value of Receive Power',
    'Sink NE Current Value of Receive Power',
    'Source NE Max Value of Transmit Power of 24-Hour PM',
    'Sink NE Max Value of Transmit Power of 24-Hour PM',
    'Source NE Min Value of Transmit Power of 24-Hour PM',
    'Sink NE Min Value of Transmit Power of 24-Hour PM',
    'Source NE Max Value of Receive Power of 24-Hour PM',
    'Sink NE Max Value of Receive Power of 24-Hour PM',
    'Source NE Min Value of Receive Power of 24-Hour PM',
    'Sink NE Min Value of Receive Power of 24-Hour PM',
    'Source NE Guaranteed E1 Capacity',
    'Sink NE Guaranteed E1 Capacity',
    'Source NE Occupied E1 Capacity',
    'Sink NE Occupied E1 Capacity',
    'Source NE E1 Capacity Usage (%)',
    'Sink NE E1 Capacity Usage (%)',
    'Source NE Ethernet Capacity (Mbit/s)',
    'Sink NE Ethernet Capacity (Mbit/s)',
    'Source NE Max. Ethernet Throughput (kbps)',
    'Sink NE Max. Ethernet Throughput (kbps)',
    'Source NE Min. Ethernet Throughput (kbps)',
    'Sink NE Min. Ethernet Throughput (kbps)',
    'Source NE Average Ethernet Throughput (kbps)',
    'Sink NE Average Ethernet Throughput (kbps)',
    'Source NE ATPC Upper Threshold',
    'Sink NE ATPC Upper Threshold',
    'Source NE ATPC Lower Threshold',
    'Sink NE ATPC Lower Threshold',
    'Source NE ATPC Upper Automatic Threshold',
    'Sink NE ATPC Upper Automatic Threshold',
    'Source NE ATPC Lower Automatic Threshold',
    'Sink NE ATPC Lower Automatic Threshold',
    'Link ID',
    'Site Distance',
    'Source PLA ID',
    'Sink PLA ID'
);